修复最新demo切换vue3时编译失败的问题;
umijs/qiankun pull request #1135
Opened 2020-12-08 08:23 UTC by HiNaruta

##### Checklist

- [√] `npm test` passes
- [√] tests are included
- [√] documentation is changed or added
- [√] commit message follows commit guidelines

##### Description of change

- any feature?
- close https://github.com/umijs/qiankun/ISSUE_URL

2020-12-08 09:01 UTC, gongshun requested changes
在 vue3 中，组件可以包含多个根节点 
https://v3.cn.vuejs.org/guide/migration/fragments.html#%E7%89%87%E6%AE%B5

2020-12-08 09:10 UTC, gongshun reviewed
原写法也是正确的，实验性的功能 
https://v3.cn.vuejs.org/guide/migration/introduction.html#%E5%80%BC%E5%BE%97%E6%B3%A8%E6%84%8F%E7%9A%84%E6%96%B0%E7%89%B9%E6%80%A7

https://github.com/vuejs/rfcs/blob/sfc-improvements/active-rfcs/0000-sfc-style-variables.md

2020-12-08 09:19 UTC, HiNaruta commented
> 原写法也是正确的，实验性的功能
> https://v3.cn.vuejs.org/guide/migration/introduction.html#%E5%80%BC%E5%BE%97%E6%B3%A8%E6%84%8F%E7%9A%84%E6%96%B0%E7%89%B9%E6%80%A7
> 
> https://github.com/vuejs/rfcs/blob/sfc-improvements/active-rfcs/0000-sfc-style-variables.md



> 原写法也是正确的，实验性的功能
> https://v3.cn.vuejs.org/guide/migration/introduction.html#%E5%80%BC%E5%BE%97%E6%B3%A8%E6%84%8F%E7%9A%84%E6%96%B0%E7%89%B9%E6%80%A7
> 
> https://github.com/vuejs/rfcs/blob/sfc-improvements/active-rfcs/0000-sfc-style-variables.md

但是在当前环境下编译已经无法通过了, 点击过去即是报错黑屏

2020-12-08 10:19 UTC, gongshun commented
> 在当前环境下编译已经无法通过了, 点击过去即是报错黑

 我又试了下， `yarn install` 安装依赖，然后 `npm start` 可以正常跑起来，点击也不会报错

2020-12-08 10:25 UTC, HiNaruta commented
> > 在当前环境下编译已经无法通过了, 点击过去即是报错黑
> 
> 我又试了下， `yarn install` 安装依赖，然后 `npm start` 可以正常跑起来，点击也不会报错


![image](https://user-images.githubusercontent.com/26237833/101471581-76682300-3982-11eb-8664-f23824db50d5.png)

2020-12-08 10:30 UTC, gongshun commented
> ![image](https://user-images.githubusercontent.com/26237833/101471581-76682300-3982-11eb-8664-f23824db50d5.png)

看了下 https://github.com/vuejs/rfcs/pull/231 ，写法的确修改了，前两个提交不需要，只修改 `<style vars>`  问题即可

2020-12-08 10:33 UTC, HiNaruta commented
> > ![image](https://user-images.githubusercontent.com/26237833/101471581-76682300-3982-11eb-8664-f23824db50d5.png)
> 
> 看了下 [vuejs/rfcs#231](https://github.com/vuejs/rfcs/pull/231) ，写法的确修改了，前两个提交不需要，只修改 `<style vars>` 问题即可

那单独合并该修改即可, 还是需要发起新的

> > ![image](https://user-images.githubusercontent.com/26237833/101471581-76682300-3982-11eb-8664-f23824db50d5.png)
> 
> 看了下 [vuejs/rfcs#231](https://github.com/vuejs/rfcs/pull/231) ，写法的确修改了，前两个提交不需要，只修改 `<style vars>` 问题即可

那单独合并修改该次提交即可, 还是需要发起新的pull request?

2020-12-08 11:25 UTC, gongshun commented
> 单独合并修改该次提交即可, 还是需要发起新的pull request?

重新开一个吧

2020-12-10 11:00 UTC, kuitos commented
close via https://github.com/umijs/qiankun/pull/1137

2020-12-10 11:00 UTC, closed without merging