📝 add cookbook
umijs/qiankun pull request #1167
Opened 2020-12-20 09:55 UTC by gongshun

##### Checklist

- [x] documentation is changed or added

##### Description of change

- any feature? 文档 新增了新手教程
- close https://github.com/umijs/qiankun/pull/559

2020-12-21 10:47 UTC, kuitos commented
跟 https://github.com/umijs/qiankun/pull/559 这个做过合并么

2020-12-21 11:09 UTC, gongshun commented
没有，重新整理了一份

2020-12-24 04:32 UTC, kuitos requested changes

2020-12-24 04:32 UTC, kuitos commented on docs/cookbook/README.zh.md
> +import { registerMicroApps, start, initGlobalState } from 'qiankun';
initGlobalState 不要在教程里暴露出来了，后面单独给一个栏目讲怎么做微应用通信吧。

initGlobalState 这个方式现在看来不是推荐的路径

2020-12-24 04:33 UTC, gongshun commented on docs/cookbook/README.zh.md
> +import { registerMicroApps, start, initGlobalState } from 'qiankun';
好的

2020-12-24 04:58 UTC, kuitos requested changes

2020-12-24 04:58 UTC, kuitos commented on docs/cookbook/README.zh.md
> +  title: 新手教程
改成 「入门教程」? 「入门」感觉比 「新手」更中性一点

2020-12-24 04:58 UTC, kuitos commented on docs/cookbook/README.zh.md
> +#### Angular 微应用
这个子类顺序调整一下，按照 react -> vue -> angular 的顺序来吧

2020-12-24 04:58 UTC, kuitos commented on docs/cookbook/README.zh.md
> +2. `history` 路由需要设置路由 `base`，值和它的 `activeRule` 是一样的，`hash` 模式无需设置。
hash 模式应该也需要设置 base 吧？有多个子应用都是用的 hash 模式时，还是需要通过 base 来区分

2020-12-24 04:58 UTC, kuitos commented on docs/cookbook/README.zh.md
> +### 微应用的路由模式如何选择
这以下的都放到 cookbook，这以上的都作为一个独立的 tutorial 放到 guide 目录下吧

2020-12-24 04:58 UTC, kuitos commented on docs/cookbook/README.zh.md
> +## 从 1.x 版本升级到 2.x 版本
升级指南的话可以在 CHANGELOG 那一个地方搞一个多级目录出来，比如 

- 版本日志
  -- 升级到 2.x
  -- CHANGELOG

 类似 vue 的
![image](https://user-images.githubusercontent.com/5206843/103061784-56be3500-45e7-11eb-9e03-a5c233612d7e.png)

用法可以看下 dumi 的文档 https://d.umijs.org/zh-CN/config#navs

2020-12-24 13:24 UTC, gongshun commented on docs/cookbook/README.zh.md
> +### 微应用的路由模式如何选择
已调整

2020-12-24 13:24 UTC, gongshun commented on docs/cookbook/README.zh.md
> +2. `history` 路由需要设置路由 `base`，值和它的 `activeRule` 是一样的，`hash` 模式无需设置。
已修正

2020-12-24 13:24 UTC, gongshun commented on docs/cookbook/README.zh.md
> +#### Angular 微应用
已调整

2020-12-24 13:25 UTC, gongshun commented on docs/cookbook/README.zh.md
> +  title: 新手教程
已修正

2020-12-24 13:26 UTC, gongshun commented on docs/cookbook/README.zh.md
> +## 从 1.x 版本升级到 2.x 版本
放到了这个位置

![image](https://user-images.githubusercontent.com/29347231/103091253-8f353180-462e-11eb-8fe8-304bc83f8126.png)

原本 1.x 是单独作为一个导航的，考虑后续会发布新版本，旧版本都需要放链接

2020-12-30 04:49 UTC, kuitos submitted a review, later dismissed

2020-12-30 04:49 UTC, kuitos commented on .umirc.ts
> +        title: 'other version',
```suggestion
        title: 'Version Notice',
```

2020-12-30 04:49 UTC, kuitos commented on .umirc.ts
>        { title: 'Changelog', path: 'https://github.com/umijs/qiankun/releases' },
```suggestion
```

2020-12-30 04:49 UTC, kuitos commented on .umirc.ts
> +          { title: '1.x version', path: 'https://v1.qiankun.umijs.org/' },
```suggestion
          { title: 'Changelog', path: 'https://github.com/umijs/qiankun/releases' },
          { title: '1.x version', path: 'https://v1.qiankun.umijs.org/' },
```

2020-12-30 04:49 UTC, kuitos commented on .umirc.ts
> +          { title: 'upgrade guide', path: '/cookbook#upgrade-from-1x-version-to-2x-version' },
```suggestion
          { title: 'Upgrade Guide', path: '/cookbook#upgrade-from-1x-version-to-2x-version' },
```

2020-12-30 04:49 UTC, kuitos commented on .umirc.ts
>        { title: '发布日志', path: 'https://github.com/umijs/qiankun/releases' },
```suggestion
```

2020-12-30 04:49 UTC, kuitos commented on .umirc.ts
> +          { title: '1.x 版本', path: 'https://v1.qiankun.umijs.org/zh/' },
```suggestion
          { title: '发布日志', path: 'https://github.com/umijs/qiankun/releases' },
          { title: '1.x 版本', path: 'https://v1.qiankun.umijs.org/zh/' },
```

2020-12-30 04:49 UTC, kuitos commented on .umirc.ts
> +        title: '其他版本',
```suggestion
        title: '版本公告',
```

2020-12-30 04:52 UTC, kuitos commented on .umirc.ts
> +          { title: '1.x version', path: 'https://v1.qiankun.umijs.org/' },
```suggestion
          { title: 'Upgrade Guide', path: '/cookbook#upgrade-from-1x-version-to-2x-version' },
```

2020-12-30 04:52 UTC, kuitos commented on .umirc.ts
> +          { title: 'Upgrade Guide', path: '/cookbook#upgrade-from-1x-version-to-2x-version' },
```suggestion
          { title: '1.x Version', path: 'https://v1.qiankun.umijs.org/' },
```

2020-12-30 04:53 UTC, kuitos commented on .umirc.ts
> +          { title: '1.x 版本', path: 'https://v1.qiankun.umijs.org/zh/' },
```suggestion
          { title: '升级指南', path: '/zh/cookbook#从-1x-版本升级到-2x-版本' },
```

2020-12-30 04:53 UTC, kuitos commented on .umirc.ts
> +          { title: '升级指南', path: '/zh/cookbook#从-1x-版本升级到-2x-版本' },
```suggestion
          { title: '1.x 版本', path: 'https://v1.qiankun.umijs.org/zh/' },
```

2020-12-30 04:58 UTC, kuitos approved these changes
Great Job!

2020-12-30 05:01 UTC, merged