🐛 Make sure singular is always false when using loadMicroApp
umijs/qiankun pull request #1168
Opened 2020-12-20 12:42 UTC by gongshun

##### Checklist

- [x] `npm test` passes
- [x] tests are included
- [x] commit message follows commit guidelines

##### Description of change

如果先使用 `start` 函数，默认的 `singular` 值会变成 `true`，再使用 `loadMicroApp` ， `singular`  就还是 `true`

2020-12-21 08:48 UTC, kuitos requested changes

2020-12-21 08:48 UTC, kuitos commented on src/apis.ts
> +    frameworkConfiguration.singular = false;
这个会导致路由配置的应用被强行改成 singular false 吧，应该是需要在 loadMicroApp 读 singular 的地方处理一下

2020-12-21 09:05 UTC, gongshun commented on src/apis.ts
> +    frameworkConfiguration.singular = false;
是的，这样写有问题，我改一下

2020-12-23 07:49 UTC, kuitos requested changes

2020-12-23 07:49 UTC, kuitos commented on src/apis.ts
> +
这里是多了两个空格？prettier 没生效么？

2020-12-23 07:51 UTC, gongshun commented on src/apis.ts
> +
提交的时候 ，lint 校验了全部文件，旧代码有些不符合规范，就报错了，然后就没有触发 prettier ，提交不上，删除 node_modules 提交的，就绕过了 lint

2020-12-23 11:47 UTC, kuitos commented on src/apis.ts
> +
好像 eslint 规则更新了..

我修一下 eslint

2020-12-23 12:01 UTC, gongshun commented on src/apis.ts
> +
我提交的时候 commit 没问题，push 触发了全部文件的校验，这个人也是一样 https://github.com/umijs/qiankun/issues/1171。但是看配置，commit 只会校验修改的文件吧，push 则是触发单元测试，但是实际上就是 push 触发了全部文件的校验，今天修改钉钉群二维码，又是正常的，就很迷

2020-12-23 14:01 UTC, kuitos commented on src/apis.ts
> +
你这个先手动把空格改回去吧，然后把这个 pr 合掉

2020-12-23 14:03 UTC, kuitos commented
这个我记得是有关联的 issue？有的话加到 pr 描述里关联 close 一下

2020-12-23 14:25 UTC, gongshun commented
> 这个我记得是有关联的 issue？有的话加到 pr 描述里关联 close 一下

空格去掉了，没有关联issue，在钉钉群里有人提出来的

2020-12-24 04:28 UTC, kuitos commented
合一下 master 分支，lint 问题修复了

2020-12-24 04:36 UTC, gongshun commented
> 合一下 master 分支，lint 问题修复了

合并了

2020-12-24 04:59 UTC, kuitos approved these changes

2020-12-24 04:59 UTC, merged