Fix/check performance
umijs/qiankun pull request #1173
Opened 2020-12-22 09:12 UTC by haitaodesign

##### Checklist

- [x] `npm test` passes
- [x ] tests are included
- [ ] documentation is changed or added
- [x ] commit message follows commit guidelines

##### Description of change

- any feature?
- close https://github.com/umijs/qiankun/ISSUE_URL

2020-12-22 09:15 UTC, Deturium commented
你是在什么环境遇到了错误，这个 API 兼容性应该还挺好的

![image](https://user-images.githubusercontent.com/19731097/102871334-4425ed80-4479-11eb-9254-c44001ff0497.png)

2020-12-22 09:24 UTC, haitaodesign commented
> 你是在什么环境遇到了错误，这个 API 兼容性应该还挺好的
> 
> ![image](https://user-images.githubusercontent.com/19731097/102871334-4425ed80-4479-11eb-9254-c44001ff0497.png)

桌面客户端下内置浏览器，把这个给屏蔽了

2020-12-23 11:59 UTC, kuitos requested changes

2020-12-23 11:59 UTC, kuitos commented on src/loader.ts
>              const marks = performance.getEntriesByName(markName, 'mark');
把 performance.getEntriesByName 也封装成一个方法放到 utils 吧，跟 performanceMark 保持一致

2020-12-23 12:29 UTC, haitaodesign commented on src/loader.ts
>              const marks = performance.getEntriesByName(markName, 'mark');
好的，我改下代码

2020-12-24 02:45 UTC, haitaodesign commented on src/loader.ts
>              const marks = performance.getEntriesByName(markName, 'mark');
@kuitos 代码改好了，你看下

2020-12-24 04:27 UTC, kuitos commented
合一下 master 分支，eslint 的问题修复了，代码需要走一下 lint hook

2020-12-24 05:40 UTC, haitaodesign commented
> 合一下 master 分支，eslint 的问题修复了，代码需要走一下 lint hook

ok

2020-12-24 06:59 UTC, kuitos approved these changes

2020-12-24 06:59 UTC, kuitos commented on src/utils.ts
> +export function performanceGetEntriesByName(markName: string, type?: string | undefined) {
```suggestion
export function performanceGetEntriesByName(markName: string, type?: string) {
```

2020-12-24 07:23 UTC, kuitos approved these changes

2020-12-24 07:23 UTC, kuitos commented on src/loader.ts
> +  performanceGetEntriesByName
```suggestion
```

2020-12-24 07:23 UTC, kuitos commented on src/loader.ts
>    performanceMeasure,
```suggestion
  performanceMeasure,
  performanceGetEntriesByName,
```

2020-12-24 07:47 UTC, merged

2020-12-24 07:47 UTC, kuitos commented
Thanks for your nice work!