docs: update the link of example without bundler
umijs/qiankun pull request #1274
Opened 2021-02-20 09:38 UTC by zjffun

##### Checklist

- [x] documentation is changed or added
- [ ] commit message follows commit guidelines (https://github.com/umijs/qiankun/blob/master/CONTRIBUTING.md is broken)

##### Description of change

This link was added in #559 and its content was removed in #1167 . So I updated this link to the purehtml example.

2021-02-22 02:00 UTC, gongshun reviewed
链接到 https://qiankun.umijs.org/zh/guide/tutorial#%E9%9D%9E-webpack-%E6%9E%84%E5%BB%BA%E7%9A%84%E5%BE%AE%E5%BA%94%E7%94%A8 这里吧。

2021-02-22 04:38 UTC, zjffun commented
改好了

2021-02-22 05:44 UTC, ycjcl868 commented on docs/guide/getting-started.md
> +Refer to [example without bundler](https://qiankun.umijs.org/guide/tutorial#micro-app-built-without-webpack)
不用写域名，这样本地 dev 跳转到线上去了

2021-02-22 05:53 UTC, kuitos requested changes

2021-02-22 05:53 UTC, kuitos commented on docs/guide/getting-started.md
> +Refer to [example without bundler](https://qiankun.umijs.org/guide/tutorial#micro-app-built-without-webpack)
+1

2021-02-22 05:53 UTC, kuitos commented on docs/guide/getting-started.zh.md
> +无 webpack 等构建工具的应用接入方式请见[这里](https://qiankun.umijs.org/zh/guide/tutorial#%E9%9D%9E-webpack-%E6%9E%84%E5%BB%BA%E7%9A%84%E5%BE%AE%E5%BA%94%E7%94%A8)
同上一条

2021-02-22 06:16 UTC, zjffun commented on docs/guide/getting-started.zh.md
> +无 webpack 等构建工具的应用接入方式请见[这里](https://qiankun.umijs.org/zh/guide/tutorial#%E9%9D%9E-webpack-%E6%9E%84%E5%BB%BA%E7%9A%84%E5%BE%AE%E5%BA%94%E7%94%A8)
我试了下，配置成 `tutorial.zh.md#非-webpack-构建的微应用` dumi 处理后会跳转到这种地址 `/qiankun/zh/guide/tutorial.zh#非-webpack-构建的微应用` （多了 `.zh`）。有什么配置或处理方式么？

2021-02-26 06:49 UTC, kuitos commented on docs/guide/getting-started.zh.md
> +无 webpack 等构建工具的应用接入方式请见[这里](https://qiankun.umijs.org/zh/guide/tutorial#%E9%9D%9E-webpack-%E6%9E%84%E5%BB%BA%E7%9A%84%E5%BE%AE%E5%BA%94%E7%94%A8)
改成 /zh/guide/tutorial#%E9%9D%9E-webpack-%E6%9E%84%E5%BB%BA%E7%9A%84%E5%BE%AE%E5%BA%94%E7%94%A8

这种也不行么？

2021-02-27 04:52 UTC, zjffun commented on docs/guide/getting-started.zh.md
> +无 webpack 等构建工具的应用接入方式请见[这里](https://qiankun.umijs.org/zh/guide/tutorial#%E9%9D%9E-webpack-%E6%9E%84%E5%BB%BA%E7%9A%84%E5%BE%AE%E5%BA%94%E7%94%A8)
这样没问题。之前想试着让这个链接在vscode里也能正常跳转，刚才看了下 dumi 的文档没有相关的配置

2021-03-01 10:41 UTC, kuitos approved these changes
Thanks for your nice work!

2021-03-01 10:41 UTC, merged