fixbug1352，适配vue3 并修改代码缩进
umijs/qiankun pull request #1379
Opened 2021-04-09 02:47 UTC by WangHao1221

1.只是修改锁定依赖即可
2.npm test测试通过
3.eslint校验通过

2021-04-09 02:56 UTC, gongshun submitted a review, later dismissed

2021-04-09 07:29 UTC, kuitos commented
是碰到了啥问题需要锁版本才能解？

2021-04-09 07:34 UTC, WangHao1221 commented
vue3模板 直接按照流程安装依赖 启动的时候 报错，如果不锁定版本，会提示一堆连锁报错



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Kuitos ***@***.***&gt;
发送时间: 2021年4月9日 15:29
收件人: umijs/qiankun ***@***.***&gt;
抄送: peterWang ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[umijs/qiankun] fixbug1352，适配vue3 并修改代码缩进 (#1379)

2021-04-09 09:04 UTC, kuitos commented
这个是最近出现的吗？我记得以前 vue3 demo 是能正常启动的吧？ @gongshun

2021-04-09 09:40 UTC, gongshun commented
> 这个是最近出现的吗？我记得以前 vue3 demo 是能正常启动的吧？ @gongshun

是最近出现的，以前可以正常启动，依赖更新了跑不起来，https://github.com/umijs/qiankun/issues/1352

2021-04-09 10:16 UTC, WangHao1221 commented
应该是最近 而且我用的web pack5 和node14



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Kuitos ***@***.***&gt;
发送时间: 2021年4月9日 17:04
收件人: umijs/qiankun ***@***.***&gt;
抄送: peterWang ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[umijs/qiankun] fixbug1352，适配vue3 并修改代码缩进 (#1379)





 
这个是最近出现的吗？我记得以前 vue3 demo 是能正常启动的吧？ @gongshun
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-04-09 10:17 UTC, WangHao1221 commented
是的 应该是新的依赖不兼容 所以最好锁定版本



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: gongshun ***@***.***&gt;
发送时间: 2021年4月9日 17:41
收件人: umijs/qiankun ***@***.***&gt;
抄送: peterWang ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[umijs/qiankun] fixbug1352，适配vue3 并修改代码缩进 (#1379)





  
这个是最近出现的吗？我记得以前 vue3 demo 是能正常启动的吧？ @gongshun
  
是最近出现的，以前可以正常启动，依赖更新了跑不起来，#1352
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-04-12 03:16 UTC, kuitos commented
咦？为啥关了？是依赖没问题了？

2021-04-12 04:16 UTC, WangHao1221 commented
呀 我以为你已经合并了，新版兼容是要配置的 我测试好几遍了的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Kuitos ***@***.***&gt;
发送时间: 2021年4月12日 11:16
收件人: umijs/qiankun ***@***.***&gt;
抄送: peterWang ***@***.***&gt;, State change ***@***.***&gt;
主题: 回复：[umijs/qiankun] fixbug1352，适配vue3 并修改代码缩进 (#1379)

2021-04-12 09:21 UTC, kuitos commented
我用 vue-cli 建了个 vue3 项目试了下，应该只需要加这两个版本依赖就可以了：
```diff
+ "less": "^3.0.4",
+ "less-loader": "^5.0.0"
```

@WangHao1221 @gongshun 试下？

2021-04-12 10:48 UTC, WangHao1221 commented
这个也是可以实现的 我测试了 所以说得锁定一下版本 不然坑就不少😄



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Kuitos ***@***.***&gt;
发送时间: 2021年4月12日 17:21
收件人: umijs/qiankun ***@***.***&gt;
抄送: peterWang ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[umijs/qiankun] fixbug1352，适配vue3 并修改代码缩进 (#1379)

2021-04-12 15:29 UTC, gongshun commented
> 我用 vue-cli 建了个 vue3 项目试了下，应该只需要加这两个版本依赖就可以了：
> + "less": "^3.0.4",
> + "less-loader": "^5.0.0"

试了下，只加这两个依赖，可以跑起来

2021-04-13 00:00 UTC, WangHao1221 commented
是的 昨天我也测了 可以的 这个版本真害人 😄



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: gongshun ***@***.***&gt;
发送时间: 2021年4月12日 23:30
收件人: umijs/qiankun ***@***.***&gt;
抄送: peterWang ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[umijs/qiankun] fixbug1352，适配vue3 并修改代码缩进 (#1379)





  
我用 vue-cli 建了个 vue3 项目试了下，应该只需要加这两个版本依赖就可以了：
  
"less": "^3.0.4", 

"less-loader": "^5.0.0" 
  
试了下，只加这两个依赖，可以跑起来
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-04-13 06:23 UTC, kuitos commented
> > 我用 vue-cli 建了个 vue3 项目试了下，应该只需要加这两个版本依赖就可以了：
> > 
> > * "less": "^3.0.4",
> > * "less-loader": "^5.0.0"
> 
> 试了下，只加这两个依赖，可以跑起来

那就用这两个依赖吧，跟 vue-cli 创建出来的保持一致。 @WangHao1221 pr 修改一下？

2021-04-13 06:31 UTC, kuitos requested changes

2021-04-13 06:31 UTC, kuitos commented on examples/vue3/package.json
> +    "less": "3.9.0",
```suggestion
    "less": "^3.0.4",
```

2021-04-13 06:31 UTC, kuitos commented on examples/vue3/package.json
> +    "less-loader": "4.1.0",
```suggestion
    "less-loader": "^5.0.0",
```

2021-04-13 06:31 UTC, kuitos commented on examples/vue3/package.json
> +    "style-resources-loader": "^1.4.1"
```suggestion
```

2021-04-13 06:32 UTC, kuitos commented
我直接 suggestion commit 了

2021-04-13 06:35 UTC, merged

2021-04-13 06:36 UTC, WangHao1221 commented
好的好的 看到了 这样的确方便一些，条条大路通罗马😄



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Kuitos ***@***.***&gt;
发送时间: 2021年4月13日 14:32
收件人: umijs/qiankun ***@***.***&gt;
抄送: peterWang ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[umijs/qiankun] fixbug1352，适配vue3 并修改代码缩进 (#1379)





 
我直接 suggestion commit 了
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.