fix: proxy sandbox overwrite read-only fields exception.
umijs/qiankun pull request #2016
Opened 2022-03-26 12:32 UTC by xioozq

##### Checklist
- [x] `npm test` passes
- [x] commit message follows commit guidelines

##### Description of change

- 修复proxy对只读属性重写导致的报错

#2015

2022-03-30 13:37 UTC, kuitos commented on src/utils.ts
> +export function isOverWritable(target: any, p?: any) {
isPropertyReadonly？

2022-05-27 02:49 UTC, kuitos requested changes

2022-05-27 02:49 UTC, kuitos commented on src/utils.ts
> +  let propertyDescriptor = null;
这里需要加一下 cache，参考上面几个 isXXX 的实现，这块会被频繁访问会有性能问题

2022-05-28 14:13 UTC, xioozq commented on src/utils.ts
> +  let propertyDescriptor = null;
done

2022-05-28 14:15 UTC, xioozq commented
> 单测需要补一下

done.

2022-05-29 15:06 UTC, closed without merging

2022-05-30 06:31 UTC, kuitos commented
这个不小心关掉了，方便重新提交一下 pr 吗