fix: document.all proxy error in naughtySafari
umijs/qiankun pull request #2465
Opened 2023-04-14 03:39 UTC by showonne

因为:
1: 
/**
 * in safari
 * typeof document.all === 'undefined' // true
 * typeof document.all === 'function' // true
 * We need to discriminate safari for better performance */ 2:  
`isBoundedFunction` 里用到了 `fn.name.indexOf`
导致用到了 `document.all` 的地方会报错

##### Checklist

- [ ] `npm test` passes
- [ ] tests are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

- any feature?
- close https://github.com/umijs/qiankun/ISSUE_URL

2023-04-18 13:20 UTC, kuitos commented
具体报什么错能提供下吗？

2023-04-19 01:30 UTC, showonne commented
> 什么错能提供下
已经 patch 上线了没保留截图，就是普通的空指针报错，Cannot read properties of undefined (reading 'indexOf')，因为 `patchDocument` 里 typeof value === 'function' 的判断对 `document.all` 也是 true，所以会进到 `isBoundedFunction` 的判断，里面用到了 `fn.name.indexOf`，导致空指针异常

2023-04-19 06:38 UTC, kuitos requested changes

2023-04-19 06:38 UTC, kuitos commented on src/sandbox/patchers/dynamicAppend/forStrictSandbox.ts
>          if (typeof value === 'function' && !isBoundedFunction(value)) {
直接把这里的 `typeof value === 'function'` 判断换成 isCallable 就可以了，里面针对 Safari 做了处理

2023-04-19 08:24 UTC, showonne commented on src/sandbox/patchers/dynamicAppend/forStrictSandbox.ts
>          if (typeof value === 'function' && !isBoundedFunction(value)) {
done

2023-04-19 09:41 UTC, kuitos approved these changes
LGTM

2023-04-19 09:46 UTC, merged