fix: Fixed the problem that the cssText attribute cannot be obtained …
umijs/qiankun pull request #2532
Opened 2023-06-13 16:10 UTC by aique127

##### Checklist

- [x] `npm test` passes
- [x] tests are included
- [x] documentation is changed or added
- [x] commit message follows commit guidelines

##### Description of change
fix: Fixed the problem that the cssText attribute cannot be obtained when @keyfram has a -webkit prefix style in IE11

ie11环境下，当@keyframe带有-webkit-私有前缀时，使用cssRules获取不到cssText导致报错: 找不到成员。
例如使用autoprefixe插件自动添加前缀
```css
// 转换前
@keyframes donghua {
    from {
        transform: rotate(0deg);
    }
    to {
        transform: rotate(360deg);
    }
}
// autoprefixe插件转换后
@keyframes donghua {
    from {
        transform: rotate(0deg);
        -webkit-transform: rotate(0deg);
    }
    to {
        transform: rotate(360deg);
        -webkit-transform: rotate(360deg);
    }
}
```
这或许上面是autoprefixe插件的bug，正确的转换应该是？
```css
@keyframes donghua {
    from {
        transform: rotate(0deg);
    }
    to {
        transform: rotate(360deg);
    }
}
@-webkit-keyframes donghua {
    from {
        -webkit-transform: rotate(0deg);
    }
    to {
        -webkit-transform: rotate(360deg);
    }
}
```
**希望能在qiankun代码里进行错误捕获。防止获取cssText报错**

- close https://github.com/umijs/qiankun/issues/2527

2023-06-26 01:57 UTC, wangdaodao commented
期待早日合并：）

2023-06-27 08:57 UTC, kuitos requested changes

2023-06-27 08:57 UTC, kuitos commented on src/sandbox/patchers/css.ts
> +          try {
不建议这里 try catch，可以参考这个方案修复 https://github.com/gregnb/react-to-print/pull/99/files

2023-06-27 14:29 UTC, aique127 commented on src/sandbox/patchers/css.ts
> +          try {
已经重新提交了：）

2023-06-28 03:23 UTC, kuitos approved these changes
Nice work~

2023-06-28 04:12 UTC, merged