Feat/webpack plugin
umijs/qiankun pull request #2699
Opened 2023-09-25 11:17 UTC by nayonglin

##### Description of change

- #2678 完成webpack插件第一版本开发，支持自动修改output相关属性。
- 增加webpack插件README.md
- webpack4和5项目改造为qiankun子应用直接使用该插件即可。
- 验证webpack4和webpack5使用正常。
- examples目录新增react15-plugin和react16-plugin示例，分别对应webpack4和webpack5项目。

2023-09-25 13:32 UTC, kuitos requested changes
好像还没有设置 entry script 的功能？

2023-09-25 13:32 UTC, kuitos commented on packages/sandbox/src/core/sandbox/globals.ts
>  // generated from https://github.com/sindresorhus/globals/blob/main/globals.json es2015 part
这个不要提交

2023-09-25 13:32 UTC, kuitos commented on packages/qiankunOutputPlugin/src/index.js
> +const fs = require('fs');
改成 ts 版本？

2023-09-25 13:32 UTC, kuitos commented on packages/qiankunOutputPlugin/package.json
> +  "name": "qiankun-plugin",
@qiankunjs/webpack-plugin

2023-09-25 13:45 UTC, kuitos commented
OK，那我先标记成 WIP

2023-09-25 17:23 UTC, nayonglin commented on pnpm-lock.yaml
@kuitos pnpm-lock.yaml需不需要添加到ignore里面，我看yarn.lock和package-lock.json都在ignore里面

2023-09-26 02:16 UTC, aladdin-add commented on pnpm-lock.yaml
不要！忽略了其它2个是因为我们用的 pnpm，而不是npm/yarn. :)

2023-09-26 03:25 UTC, nayonglin commented on pnpm-lock.yaml
> 不要！忽略了其它2个是因为我们用的 pnpm，而不是npm/yarn. :)

嗯嗯，理解

2023-09-26 06:35 UTC, nayonglin commented on packages/qiankunOutputPlugin/src/index.js
> +const fs = require('fs');
done

2023-09-28 05:54 UTC, aladdin-add commented on packages/qiankunOutputPlugin/package.json
目录的名字最好和包的名字保持一致。e.g. `webpack-plugin`
另外好像其它的包是连字符风格的，而不是驼峰 :)

2023-09-28 05:56 UTC, aladdin-add commented on packages/qiankunOutputPlugin/src/index.ts
> +import * as path from 'path';
Q: 好奇直接用`import fs from 'fs';`会有什么问题么？ 😄

2023-09-28 05:59 UTC, aladdin-add commented on packages/qiankunOutputPlugin/src/index.ts
> +module.exports = QiankunPlugin;
使用ts的话，统一使用 esm， 最好不要混用 esm/cjs.

2023-09-28 06:00 UTC, aladdin-add commented on packages/qiankunOutputPlugin/README.md
> +`qiankun-plugin` 是一个为 [qiankun](https://github.com/umijs/qiankun) 微前端框架设计的 Webpack 插件，用于简化和自动化与 qiankun 集成的一些常见配置。
@qiankunjs/webpack-plugin

2023-09-28 07:13 UTC, kuitos commented on packages/qiankunOutputPlugin/src/index.ts
> +import * as path from 'path';
+1，是不是可以配个 no-restricted-imports 规则统一一下？

2023-09-28 09:30 UTC, nayonglin commented on packages/qiankunOutputPlugin/src/index.ts
> +import * as path from 'path';
> +1，是不是可以配个 no-restricted-imports 规则统一一下？

这个应该是禁止导入指定模块的规则？但是fs还是需要导入的呀，只是确实可以改为`import fs from 'fs';`

2023-09-28 09:44 UTC, aladdin-add commented on packages/qiankunOutputPlugin/src/index.ts
> +module.exports = QiankunPlugin;
源码统一用 esm，可以编译为 cjs.

2023-09-28 09:50 UTC, nayonglin commented on packages/qiankunOutputPlugin/src/index.ts
> +module.exports = QiankunPlugin;
> 使用ts的话，统一使用 esm， 最好不要混用 esm/cjs.

> 源码统一用 esm，可以编译为 cjs.

尝试了改为esm,`export default QiankunPlugin;`

但是业务引用cjs的时候，需要在require之后加上一个default才能引用到，感觉不太友好？
```
const QiankunPlugin = require('@qiankunjs/webpack-plugin').default
```

2023-10-07 16:48 UTC, nayonglin commented on packages/qiankunOutputPlugin/package.json
done

2023-10-07 16:48 UTC, nayonglin commented on packages/qiankunOutputPlugin/src/index.ts
> +import * as path from 'path';
done

2023-10-07 16:49 UTC, nayonglin commented on packages/qiankunOutputPlugin/README.md
> +`qiankun-plugin` 是一个为 [qiankun](https://github.com/umijs/qiankun) 微前端框架设计的 Webpack 插件，用于简化和自动化与 qiankun 集成的一些常见配置。
done

2023-10-08 02:03 UTC, aladdin-add commented on packages/qiankunOutputPlugin/src/index.ts
> +module.exports = QiankunPlugin;
哦，我了解了。那似乎我们可以选择：

1. 使用 `module.exports` => `require('@qiankunjs/webpack-plugin')`
2. 使用 `export default` => `require('@qiankunjs/webpack-plugin').default`
3. 使用命名导出：`export {QiankunPlugin}` => `import {QiankunPlugin} from '@qiankunjs/webpack-plugin'`.

2023-10-08 03:32 UTC, nayonglin commented on packages/qiankunOutputPlugin/src/index.ts
> +module.exports = QiankunPlugin;
对的，第一个最符合预期，社区其他webpack插件都是require('@qiankunjs/webpack-plugin')这样的形式导入的，代码已提交，可以再看看

2023-10-08 05:41 UTC, aladdin-add approved these changes

2023-10-08 05:41 UTC, aladdin-add commented on packages/webpack-plugin/src/index.ts
> +module.exports = QiankunPlugin;
nits: 可以加个注释说明一下为什么要这样写

2023-10-08 05:53 UTC, nayonglin commented on packages/webpack-plugin/src/index.ts
> +module.exports = QiankunPlugin;
done

2023-10-08 06:35 UTC, aladdin-add commented
lint 失败了，可以看一下么？
https://github.com/umijs/qiankun/actions/runs/6445853927/job/17500348644?pr=2699

2023-10-08 07:15 UTC, nayonglin commented
> lint 失败了，可以看一下么？ https://github.com/umijs/qiankun/actions/runs/6445853927/job/17500348644?pr=2699

done

2023-10-10 02:52 UTC, kuitos reviewed
能补一个单测吗？验证一下 build 之后的产物是否符合预期，webpack4 & 5 两个版本都需要单测覆盖一下

2023-10-10 02:52 UTC, kuitos commented on packages/webpack-plugin/README.md
README-zh.md 吧，还需要一个英文版本的

2023-10-11 11:10 UTC, nayonglin commented
> 能补一个单测吗？验证一下 build 之后的产物是否符合预期，webpack4 & 5 两个版本都需要单测覆盖一下

这里具体需要咋验证呢？能展开讲讲嘛？因为我已经在官方example验证过了，4和5都是可以的哦。

2023-10-11 11:20 UTC, nayonglin commented on packages/webpack-plugin/README.md
> README-zh.md 吧，还需要一个英文版本的

done

2023-10-11 14:07 UTC, kuitos commented
examples 是用来自测的，不能代替单测。单测主要确保 webpack build 之后产物是不是对的，比如 HTML 里正确的标记了 entry js，js chunk 里包含了 webpackJSONP 关键字

2023-10-12 02:52 UTC, kuitos commented
```js
const Plugin = require('../'); // 引入你的插件
const webpack = require('webpack');
const MemoryFs = require('memory-fs'); // 用于模拟文件系统

test('My Webpack Plugin test', done => {
  // 创建一个简单的webpack配置
  const config = {
    entry: './path/to/entry.js', // 你的入口文件
    plugins: [
      new Plugin() // 使用你的插件
    ]
  };

  const compiler = webpack(config);

  // 使用内存文件系统替换默认文件系统
  compiler.outputFileSystem = new MemoryFs();

  compiler.run((err, stats) => {
    if (err) {
      done(err);
      return;
    }

    // 在这里添加你的测试断言
    // 例如，检查生成的文件、输出的统计信息等

    done();
  });
});
```

GPT4 给的示例😂

2023-10-13 15:54 UTC, nayonglin commented
> ```js
> const Plugin = require('../'); // 引入你的插件
> const webpack = require('webpack');
> const MemoryFs = require('memory-fs'); // 用于模拟文件系统
> 
> test('My Webpack Plugin test', done => {
>   // 创建一个简单的webpack配置
>   const config = {
>     entry: './path/to/entry.js', // 你的入口文件
>     plugins: [
>       new Plugin() // 使用你的插件
>     ]
>   };
> 
>   const compiler = webpack(config);
> 
>   // 使用内存文件系统替换默认文件系统
>   compiler.outputFileSystem = new MemoryFs();
> 
>   compiler.run((err, stats) => {
>     if (err) {
>       done(err);
>       return;
>     }
> 
>     // 在这里添加你的测试断言
>     // 例如，检查生成的文件、输出的统计信息等
> 
>     done();
>   });
> });
> ```
> 
> GPT4 给的示例😂

我看现在的项目是没有使用jest的，我在我的子包引入jest可以不？以及这里要同时引入webpack4和5，还要有demo项目才行？不是那么好弄的样子😂，是否需要再评估一下？

2023-10-13 16:15 UTC, kuitos commented
单测统一用vitest吧，用例里搞几个HTML JS就可以了，不用是完整的项目

2023-10-19 07:28 UTC, nayonglin commented
> 单测统一用vitest吧，用例里搞几个HTML JS就可以了，不用是完整的项目



> examples 是用来自测的，不能代替单测。单测主要确保 webpack build 之后产物是不是对的，比如 HTML 里正确的标记了 entry js，js chunk 里包含了 webpackJSONP 关键字

这里确认下，target已经改为了window，那chunk里的关键字是不是应该判断是否包含 `window.`这个关键字？

2023-10-19 07:36 UTC, kuitos commented
对的

2023-10-19 08:17 UTC, nayonglin commented
> 对的

已增加自动化测试用例，本地 npm test通过，代码已提交，可以看看哈

2023-10-23 09:41 UTC, kuitos commented
CI 挂了，看了下是 pnpm-lock 没更新导致的，可以更新后重新提交一下吗 @nayonglin  其他应该没啥问题了

2023-10-23 12:41 UTC, nayonglin commented
> CI 挂了，看了下是 pnpm-lock 没更新导致的，可以更新后重新提交一下吗 @nayonglin 其他应该没啥问题了

已提交，再试试呢

2023-10-24 01:57 UTC, aladdin-add commented
还是报错了，我重新更新了一下，可以执行一下：
```bash
git cherry-pick b95e39be38ff41d3aa99d178c6759e2bc13896a1
```

2023-10-24 16:20 UTC, nayonglin commented
> 还是报错了，我重新更新了一下，可以执行一下：
> 
> ```shell
> git cherry-pick b95e39be38ff41d3aa99d178c6759e2bc13896a1
> ```

搞定，已提交

2023-10-25 02:22 UTC, aladdin-add commented
之前的eslint配置都是针对ts的，可能不适合cjs，我重新修改了一下 ： https://github.com/umijs/qiankun/pull/2762

2023-10-26 06:52 UTC, nayonglin commented
> 之前的eslint配置都是针对ts的，可能不适合cjs，我重新修改了一下 ： #2762

嗯嗯 ，那是等2762合入，这里才合入对吧？

2023-10-27 02:05 UTC, aladdin-add commented
已merge，请再拉一下最新的提交～

2023-10-27 03:28 UTC, nayonglin commented
> 已merge，请再拉一下最新的提交～

已合并push哈，可以看看

2023-10-27 10:10 UTC, kuitos commented
CI 挂了，看着都是 ts lint 问题，有空修一下吗？ @nayonglin

2023-10-27 11:12 UTC, nayonglin commented
> fix: eslint for plugin

done

2023-10-27 11:20 UTC, nayonglin commented
> CI 挂了，看着都是 ts lint 问题，有空修一下吗？ @nayonglin



> CI 挂了，看着都是 ts lint 问题，有空修一下吗？ @nayonglin

done

2023-10-27 12:13 UTC, kuitos commented
还是挂了，这次是prettier

2023-10-27 12:55 UTC, nayonglin commented
> CI 挂了，看着都是 ts lint 问题，有空修一下吗？ @nayonglin



> 还是挂了，这次是prettier

done

2023-10-28 15:40 UTC, nayonglin commented
> > CI 挂了，看着都是 ts lint 问题，有空修一下吗？ @nayonglin
> 
> > 还是挂了，这次是prettier
> 
> done

@kuitos 看到了新的ci报错，build的时候把tests的两个自动化测试项目也构建了，但实际应该不需要构建，是不是需要优化一下构建命令为
pnpm -r --filter=./packages/**/* --filter=!./packages/webpack-plugin/tests/*  run build

2023-10-29 10:16 UTC, kuitos commented on packages/webpack-plugin/.fatherrc.js
> +  umd: {},
不需要 umd，直接参考 loader `export { default } from '../../.fatherrc.cjs';`

2023-10-29 10:18 UTC, kuitos commented
`pnpm -r --filter=./packages/**/src run build` 这样改一下应该可以，只 build src 目录就行

2023-10-29 15:17 UTC, nayonglin commented
> `pnpm -r --filter=./packages/**/src run build` 这样改一下应该可以，只 build src 目录就行

本地试了一下，这样好像所有项目都匹配不到了，改成pnpm -r --filter=./packages/**/* --filter=!./packages/**/tests/* run build是否可行？比我之前写的更通用一些

2023-10-29 15:17 UTC, nayonglin commented
> `pnpm -r --filter=./packages/**/src run build` 这样改一下应该可以，只 build src 目录就行

本地试了一下，这样好像所有项目都匹配不到了，改成pnpm -r --filter=./packages//* --filter=!./packages//tests/* run build是否可行？比我之前写的更通用一些,代码已提交

2023-10-29 15:18 UTC, nayonglin commented on packages/webpack-plugin/.fatherrc.js
> +  umd: {},
> 不需要 umd，直接参考 loader `export { default } from '../../.fatherrc.cjs';`

done

2023-10-30 04:25 UTC, kuitos commented on package.json
> +    "build": "pnpm -r --filter=./packages/**/* --filter=!./packages/**/tests/* run build",
```suggestion
    "build": "pnpm -r --filter=./packages/*/src run build",
```

2023-10-30 04:31 UTC, kuitos commented on package.json
> +    "build": "pnpm -r --filter=./packages/*/src run build",
```suggestion
    "build": "pnpm -r --filter=./packages/**/* --filter=!./packages/**/tests/* run build,
```

2023-10-30 04:32 UTC, kuitos commented on package.json
> +    "build": "pnpm -r --filter=./packages/**/* --filter=!./packages/**/tests/* run build,
```suggestion
    "build": "pnpm -r --filter=./packages/**/* --filter=!./packages/**/tests/* run build",
```

2023-10-30 06:29 UTC, merged

2023-10-30 07:44 UTC, kuitos commented on packages/webpack-plugin/package.json
> +    "webpack-sources": "^3.2.3"
这个是直接依赖，应该放到 dependencies 里

2023-10-30 08:07 UTC, nayonglin commented on packages/webpack-plugin/package.json
> +    "webpack-sources": "^3.2.3"
> 这个是直接依赖，应该放到 dependencies 里

#2774