feat: renderer-react
umijs/qiankun pull request #2706
Opened 2023-09-26 15:04 UTC by bravepg

## MicroApp 组件

直接通过 `<MicroApp />` 组件加载（或卸载）子应用，该组件提供了 loading 以及错误捕获相关的能力：

```tsx
import { MicroApp } from '@qiankunjs/renderer-react';

export default function Page() {
  return <MicroApp name="app1" entry="http://localhost:8000" />;
}
```

当启用子应用加载动画或错误捕获能力时，子应用接受一个额外的样式类 `wrapperClassName`，渲染的结果如下所示：

```tsx
<div style={{ position: 'relative' }} className={wrapperClassName}>
  <MicroAppLoader loading={loading} />
  <ErrorBoundary error={e} />
  <MicroApp className={className} />
</div>
```

### 加载动画

启用此能力后，当子应用正在加载时，会自动显示加载动画。当子应用挂载完成变成 `MOUNTED` 状态时，加载状态结束，显示子应用内容。

直接将 `autoSetLoading` 作为参数传入即可：

```tsx
import { MicroApp } from '@qiankunjs/renderer-react';

export default function Page() {
  return <MicroApp name="app1" entry="http://localhost:8000" autoSetLoading />;
}
```

#### 自定义加载动画

如果您希望覆盖默认的加载动画样式时，可以设置一个自定义的加载组件 `loader` 作为子应用的加载动画。

```tsx
import CustomLoader from '@/components/CustomLoader';
import { MicroApp } from '@qiankunjs/renderer-react';

export default function Page() {
  return (
    <MicroApp name="app1" entry="http://localhost:8000" loader={(loading) => <CustomLoader loading={loading} />} />
  );
}
```

其中，`loading` 为 `boolean` 类型参数，为 `true` 时表示仍在加载状态，为 `false` 时表示加载状态已结束。

### 错误捕获

启用此能力后，当子应用加载出现异常时，会自动显示错误信息。可以向子应用传入 `autoCaptureError` 属性以开启子应用错误捕获能力：

```tsx
import { MicroApp } from '@qiankunjs/renderer-react';

export default function Page() {
  return <MicroApp name="app1" entry="http://localhost:8000" autoCaptureError />;
}
```

#### 自定义错误捕获

如果您希望覆盖默认的错误捕获组件样式时，可以设置一个自定义的组件 `errorBoundary` 作为子应用的错误捕获组件：

```tsx
import CustomErrorBoundary from '@/components/CustomErrorBoundary';
import { MicroApp } from '@qiankunjs/renderer-react';

export default function Page() {
  return (
    <MicroApp
      name="app1"
      entry="http://localhost:8000"
      errorBoundary={(error) => <CustomErrorBoundary error={error} />}
    />
  );
}
```

2023-09-27 10:24 UTC, kuitos reviewed
这个项目需要补下 tsx 的 lint 规则，并继承自根目录的 eslint

2023-09-27 10:24 UTC, kuitos commented on packages/ui-bindings/react/README.md
这个别删吧？原计划几个技术栈组件都放这个 ui-bindings 目录的，renderer-react 这个名字不太适合我们的场景

2023-09-27 13:03 UTC, bravepg commented on packages/ui-bindings/react/README.md
我当时想着会不会再提供其他能力，所以起的名字稍微宽泛了些，我先给调整回去好了

2023-10-08 12:52 UTC, kuitos commented
需要重新合并下主分支，应该是格式化后冲突了

2023-10-08 13:31 UTC, bravepg commented
> 需要重新合并下主分支，应该是格式化后冲突了

好的 我合并了

2023-10-08 13:35 UTC, bravepg commented on tsconfig.json
> +    "typeRoots": ["typings", "node_modules/@types", "node_modules"],
这里我增加了 node_modules，不然会出现 vitest/globals 找不到的提示
![image](https://github.com/umijs/qiankun/assets/22069371/0c478aa4-7671-46e2-bb81-12910e4e2851)

2023-10-12 12:19 UTC, bravepg commented
@kuitos 啥时候有空帮我 review 下呀？因为 next 更新有点频繁，我需要一直 merge 👀

2023-10-12 15:12 UTC, kuitos requested changes

2023-10-12 15:12 UTC, kuitos commented on packages/ui-bindings/react/src/MicroApp.tsx
> +      ?.then(() => {
同上，看来这里的 eslint 配置有点问题，类型上这些都不可能是空值

2023-10-12 15:12 UTC, kuitos commented on packages/ui-bindings/react/src/MicroApp.tsx
> +      const promise = microAppRef.current?.[key];
同上

2023-10-12 15:12 UTC, kuitos commented on packages/ui-bindings/react/src/MicroApp.tsx
> +      promise?.catch((e: Error) => {
同上

2023-10-16 07:39 UTC, bravepg commented on packages/ui-bindings/react/src/MicroApp.tsx
> +      ?.then(() => {
是的，我修改了下规则
![image](https://github.com/umijs/qiankun/assets/22069371/dbe31dd8-5050-4fde-b573-883e9c012b51)

2023-10-16 10:54 UTC, kuitos commented on .eslintrc.cjs
> +  ignorePatterns: ['.eslintrc.cjs'],
这个不 ignore 会有啥问题？

2023-10-16 10:54 UTC, kuitos commented on examples/main/index.js
> +    ReactDOM.render(
这里先不改吧，MicroApp 应该是有单独的 react 版本主应用的 demo，现在这个主应用是技术栈无关的

2023-10-16 10:54 UTC, kuitos commented on packages/ui-bindings/react/README.md
> +# qiankun react
```suggestion
# qiankun ui binding for react
```

2023-10-16 10:54 UTC, kuitos commented on packages/ui-bindings/react/README.zh-CN.md
> +# qiankun react
```suggestion
# qiankun ui binding for react
```

2023-10-16 10:58 UTC, kuitos commented on packages/ui-bindings/react/src/MicroApp.tsx
> +    errorBoundary || (propsFromParams.autoCaptureError ? (e) => <ErrorBoundary error={e} /> : null);
`(e) => <ErrorBoundary error={e} />` 这个没有类型竟然没问题？

2023-10-16 13:10 UTC, bravepg commented on .eslintrc.cjs
> +  ignorePatterns: ['.eslintrc.cjs'],
![image](https://github.com/umijs/qiankun/assets/22069371/26ab67e6-5ac2-424a-8a67-90d7e90e7148)
不加的话会存在上面截图的问题，

如果把 .eslintrc.cjs 配置在 .eslint.json 文件中，就会存在下面的问题。
![image](https://github.com/umijs/qiankun/assets/22069371/d48550c8-725b-414d-9c28-bdabd392e2a5)

需要设置 env 啥的，后面我就干脆参考 vite 的脚手架放在 ignorePatterns 里面了

2023-10-16 13:11 UTC, bravepg commented on examples/main/index.js
> +    ReactDOM.render(
那 MicroApp 现在要单独搞个 demo 出来么？

2023-10-16 13:20 UTC, bravepg commented on packages/ui-bindings/react/src/MicroApp.tsx
> +    errorBoundary || (propsFromParams.autoCaptureError ? (e) => <ErrorBoundary error={e} /> : null);
![image](https://github.com/umijs/qiankun/assets/22069371/2db46f99-e573-4eb5-adec-2ad5480110e5)
这个已经推断出来了哈

2023-10-16 15:15 UTC, kuitos commented on examples/main/index.js
> +    ReactDOM.render(
参考 2.x 的方式单独搞一个 react 的版本 https://github.com/umijs/qiankun/blob/master/examples/main/render/ReactRender.jsx

2023-10-18 02:50 UTC, kuitos commented
pr 描述记得更新一下 https://github.com/umijs/qiankun/pull/2706#issue-1913726028

2023-10-19 03:42 UTC, merged