fix: add faq
umijs/qiankun pull request #2734
Opened 2023-10-18 15:02 UTC by bravepg

添加 FAQ 以及部分格式问题

2023-10-19 03:40 UTC, kuitos requested changes

2023-10-19 03:40 UTC, kuitos commented on docs/faq/README.md
> +![](https://user-images.githubusercontent.com/22413530/109919189-41563d00-7cf3-11eb-8328-711228389d63.png) The first line is just a helper info printed by qiankun via `console.error` to help users id
这里不要改吧，之前是故意换行的

2023-10-19 03:40 UTC, kuitos commented on docs/faq/README.md
> +
这里没必要多加一个换行

2023-10-19 03:51 UTC, bravepg commented on docs/faq/README.md
> +
![image](https://github.com/umijs/qiankun/assets/22069371/6f8d1cc1-1400-428c-ab38-8b6d64e694d2)

在 readme 里换行前和换行后的渲染结果是一致的，prettier 默认就会加个换行，要按照默认的来么？

2023-10-19 03:52 UTC, bravepg commented on docs/faq/README.md
> +![](https://user-images.githubusercontent.com/22413530/109919189-41563d00-7cf3-11eb-8328-711228389d63.png) The first line is just a helper info printed by qiankun via `console.error` to help users id
为啥呀？从渲染效果上来看，图片和文本必定会换行的呀

2023-10-19 04:24 UTC, kuitos commented on docs/faq/README.md
> +![](https://user-images.githubusercontent.com/22413530/109919189-41563d00-7cf3-11eb-8328-711228389d63.png) The first line is just a helper info printed by qiankun via `console.error` to help users id
不会自动换行的，你可以本地看看效果

2023-10-19 04:25 UTC, kuitos commented on docs/faq/README.md
> +
prettier这里换行的逻辑是啥？中文版本我看又没加换行

2023-10-19 12:47 UTC, bravepg commented on docs/faq/README.md
> +
![image](https://github.com/umijs/qiankun/assets/22069371/c26432d1-2726-4e6f-a69a-31bdbe3df1a9)
中文也是会换行的呀

逻辑是：如果文本下面有个列表，则在文本和列表之间加个空行。


中文版本少了一行，是在上面发生的。
![image](https://github.com/umijs/qiankun/assets/22069371/d942e7d7-0155-4af8-9e21-621d52f18160)
列表之间，可以加空行也可以不加空行。我把中文版的补上就一致了。

2023-10-19 13:05 UTC, bravepg commented on docs/faq/README.md
> +
你这么一说，我倒是发现以前英文版跟中文版相比丢了不少东西，我都给补齐了

2023-10-20 04:06 UTC, kuitos approved these changes
LGTM

2023-10-20 04:08 UTC, merged