fix: remount-error
umijs/qiankun pull request #2751
Opened 2023-10-23 12:44 UTC by bravepg

##### Description of change

![image](https://github.com/umijs/qiankun/assets/22069371/0d269e9b-b4a6-40d3-bba9-a98e773d45e5)
由于在卸载前，已经把挂载节点的所有子元素全部移除，挂载节点本身不需要再设置为 null

- close https://github.com/umijs/qiankun/issues/2735

2023-10-23 12:53 UTC, kuitos commented
需要置为 null 的，不然 container 引用本身会被函数一直保持，导致内存泄露

2023-10-23 14:33 UTC, kuitos commented
置为 null 只是清理了引用，只是为了能垃圾回收，并不等于把 DOM 节点移除了。

2023-10-24 03:37 UTC, kuitos commented on packages/qiankun/src/core/loadApp.ts
> +            microAppContainer = container;
上面 83 行已经做过初始化了。感觉还是没找到问题原因，我用 examples 里的 react15 跟 react16 互相切换也没复现这个问题🤔

2023-10-24 04:25 UTC, bravepg commented on packages/qiankun/src/core/loadApp.ts
> +            microAppContainer = container;
examples 里面之所以没问题，是因为每次都会调用 loadMicroApp 来传递 container。
![image](https://github.com/umijs/qiankun/assets/22069371/10bf8519-0182-4523-af42-0c4b0bb2e151)


用户是这么调用的 https://github.com/lfzs/qiankun-rc-vite/blob/main/main/src/main.js#L7
![image](https://github.com/umijs/qiankun/assets/22069371/195da57b-778b-4bd7-adc2-f12472b0d614)

![image](https://github.com/umijs/qiankun/assets/22069371/5c8ef177-0c9b-41d8-9f5b-89110028d0ad)

所以每次只有初始化的时候会调用一次

2023-10-24 09:39 UTC, kuitos requested changes

2023-10-24 09:39 UTC, kuitos commented on packages/qiankun/src/core/loadApp.ts
> +            microAppContainer = container;
明白了，因为 registryMicroApp 本身是有缓存的，parcelConfigGetter 方法之后初始化一次。那 83 行删了吧，不需要了

2023-10-24 09:39 UTC, kuitos commented on packages/qiankun/src/core/loadApp.ts
> +            microAppContainer = container;
这里应该用 remountContainer

2023-10-24 09:40 UTC, kuitos commented on packages/qiankun/src/core/loadApp.ts
> +            microAppContainer = container;
明白了，因为 registerApplication 本身就是有缓存的，parcelConfigGetter 只会调用一次。

2023-10-24 09:41 UTC, kuitos commented on packages/qiankun/src/core/loadApp.ts
> +            microAppContainer = container;
83 行删了吧，不需要重复做这个事情

2023-10-24 09:48 UTC, bravepg commented on packages/qiankun/src/core/loadApp.ts
> +            microAppContainer = container;
噢噢，对

2023-10-24 11:55 UTC, kuitos approved these changes
LGTM

2023-10-24 12:00 UTC, merged