fix: correct entry script identification and webpack version detectio…
umijs/qiankun pull request #2800
Opened 2023-11-08 05:28 UTC by nayonglin

…n in Vue CLI 5

##### Checklist

- [ ] `npm test` passes
- [ ] tests are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

- any feature?
- close https://github.com/umijs/qiankun/ISSUE_URL

2023-11-08 08:23 UTC, kuitos commented on packages/webpack-plugin/README-zh.md
> +      scriptMatchPattern: /<script[^>]*src="app.*\.js"[^>]*><\/script>/g, // 可选，用于匹配要添加entry属性的script标签的正则表达式。如果不提供，默认取html最后一个script标签
改成 `entrySrcPattern`？这里应该只需要填 src 的正则就行

2023-11-08 12:49 UTC, nayonglin commented on packages/webpack-plugin/README-zh.md
> +      scriptMatchPattern: /<script[^>]*src="app.*\.js"[^>]*><\/script>/g, // 可选，用于匹配要添加entry属性的script标签的正则表达式。如果不提供，默认取html最后一个script标签
done

2023-11-08 13:11 UTC, kuitos commented on packages/webpack-plugin/README-zh.md
> +      webpackVersion: '5', // 可选，项目使用的webpack大版本,若不提供插件会自动判断当前webpack版本
不需要再指定 webpack 版本了吧？webpack5 的版本可以自动取出来，取不出来的自然就是 4 了，什么场景还需要手动指定？

2023-11-08 13:13 UTC, kuitos commented on packages/webpack-plugin/README-zh.md
> +      scriptMatchPattern: /<script[^>]*src="app.*\.js"[^>]*><\/script>/g, // 可选，用于匹配要添加entry属性的script标签的正则表达式。如果不提供，默认取html最后一个script标签
好像还没改？这里期望用户只需要配置 `entrySrcPattern: /app.*\.js/` 就行

2023-11-08 13:15 UTC, nayonglin commented on packages/webpack-plugin/README-zh.md
> +      webpackVersion: '5', // 可选，项目使用的webpack大版本,若不提供插件会自动判断当前webpack版本
> 不需要再指定 webpack 版本了吧？webpack5 的版本可以自动取出来，取不出来的自然就是 4 了，什么场景还需要手动指定？

只是作为预留能力，担心更新版本的webpack版本字段又有变化，需要去掉吗？

2023-11-08 13:20 UTC, kuitos reviewed
如果用户已经指定了 entry 就不需要处理了，这块好像漏了？

2023-11-08 13:20 UTC, kuitos commented on packages/webpack-plugin/README-zh.md
> +      webpackVersion: '5', // 可选，项目使用的webpack大版本,若不提供插件会自动判断当前webpack版本
去掉吧，现在用不到就不加

2023-11-08 15:36 UTC, nayonglin commented on packages/webpack-plugin/README-zh.md
> +      webpackVersion: '5', // 可选，项目使用的webpack大版本,若不提供插件会自动判断当前webpack版本
done

2023-11-08 15:36 UTC, nayonglin commented on packages/webpack-plugin/README-zh.md
> +      scriptMatchPattern: /<script[^>]*src="app.*\.js"[^>]*><\/script>/g, // 可选，用于匹配要添加entry属性的script标签的正则表达式。如果不提供，默认取html最后一个script标签
已加上，看成只改字段名了

2023-11-09 02:57 UTC, kuitos requested changes

2023-11-09 02:57 UTC, kuitos commented on packages/webpack-plugin/README-zh.md
> +      entrySrcPattern: /<script[^>]*src="app.*\.js"[^>]*><\/script>/g, // 可选，用于匹配要添加entry属性的script标签的正则表达式。如果不提供，默认取html最后一个script标签
文档这里还没改

2023-11-09 02:57 UTC, kuitos commented on packages/webpack-plugin/plugin.test.ts
> +    expect(jsChunkContent).toMatch(/window(\["[^"]+"\]|\.\w+)/); // 检查是否包含了 window. 或 window["..."] 关键字
这里直接检查 window.${packageName} 吧

2023-11-09 02:57 UTC, kuitos commented on packages/webpack-plugin/src/index.ts
> +    scriptTags.forEach((tag) => {
这里换成 scriptTags.some 更好

2023-11-09 02:57 UTC, kuitos commented on packages/webpack-plugin/src/index.ts
> +      ? new RegExp(`<script[^>]*src="[^"]*${options.entrySrcPattern.source}[^"]*"[^>]*></script>`, 'g')
用正则去匹配 script 很难写出没 bug 的版本，比如 script 这里有换行了
```js
<script
  src=""
>
```
更极端的 html 里有一个 script 的注释。

直接引一个 [cheerio](https://github.com/cheeriojs/cheerio) 来做 html 匹配的事情吧，可以直接用 css selector 做元素查找，会少很多 bug

2023-11-09 02:58 UTC, kuitos commented on packages/webpack-plugin/tests/webpack4/webpack.config.js
> +      entrySrcPattern: /app.12.js/,
这里应该是 `/app\.12\.js/` 吧

2023-11-09 03:00 UTC, kuitos commented on packages/webpack-plugin/src/index.ts
> +    scriptTags.forEach((tag) => {
如果 html 里找到了多个符合 entrySrcPattern 的 script，应该报错提示用户填的正则可能有问题

2023-11-22 09:54 UTC, nayonglin commented on packages/webpack-plugin/src/index.ts
> +      ? new RegExp(`<script[^>]*src="[^"]*${options.entrySrcPattern.source}[^"]*"[^>]*></script>`, 'g')
> 用正则去匹配 script 很难写出没 bug 的版本，比如 script 这里有换行了
> 
> ```js
> <script
>   src=""
> >
> ```
> 
> 更极端的 html 里有一个 script 的注释。
> 
> 直接引一个 [cheerio](https://github.com/cheeriojs/cheerio) 来做 html 匹配的事情吧，可以直接用 css selector 做元素查找，会少很多 bug

用cheerio可以，不过用户需要传入什么会比较简单一点？还需要传入正则吗？

2023-11-22 10:25 UTC, kuitos commented on packages/webpack-plugin/src/index.ts
> +      ? new RegExp(`<script[^>]*src="[^"]*${options.entrySrcPattern.source}[^"]*"[^>]*></script>`, 'g')
好像没有比正则更简单的吧？

2023-11-29 03:00 UTC, kuitos commented
@nayonglin 这周能处理一下吗？准备发 3.0 正式版了😆

2023-12-02 16:31 UTC, nayonglin commented
> @nayonglin 这周能处理一下吗？准备发 3.0 正式版了😆

嗯嗯，我明天处理一下

2023-12-03 07:27 UTC, nayonglin commented on packages/webpack-plugin/README-zh.md
> +      entrySrcPattern: /<script[^>]*src="app.*\.js"[^>]*><\/script>/g, // 可选，用于匹配要添加entry属性的script标签的正则表达式。如果不提供，默认取html最后一个script标签
> 文档这里还没改

done

2023-12-03 07:28 UTC, nayonglin commented on packages/webpack-plugin/plugin.test.ts
> +    expect(jsChunkContent).toMatch(/window(\["[^"]+"\]|\.\w+)/); // 检查是否包含了 window. 或 window["..."] 关键字
> 这里直接检查 window.${packageName} 吧

已加上包名，不过同时判断了.符号和中括号的形式，因为发现在某些场景下webpack产物是中括号的这种形式

2023-12-03 07:28 UTC, nayonglin commented on packages/webpack-plugin/src/index.ts
> +    scriptTags.forEach((tag) => {
> 如果 html 里找到了多个符合 entrySrcPattern 的 script，应该报错提示用户填的正则可能有问题

这部分已用cheerio重写

2023-12-03 07:29 UTC, nayonglin commented on packages/webpack-plugin/src/index.ts
> +      ? new RegExp(`<script[^>]*src="[^"]*${options.entrySrcPattern.source}[^"]*"[^>]*></script>`, 'g')
> 好像没有比正则更简单的吧？

done

2023-12-03 07:29 UTC, nayonglin commented on packages/webpack-plugin/tests/webpack4/webpack.config.js
> +      entrySrcPattern: /app.12.js/,
> 这里应该是 `/app\.12\.js/` 吧

done

2023-12-06 01:06 UTC, qiYuei commented
🙋‍♂️这块可以到 cli 测试了吗？

2023-12-07 07:55 UTC, qiYuei commented on packages/webpack-plugin/src/index.ts
这里还是改成 `export  class QiankunPlugin`   使用 ` const { QiankunPlugin } = require('@qiankunjs/webpack-plugin')`  用`module.exports = QiankunPlugin ` 获取不到类型

2023-12-07 07:57 UTC, qiYuei commented on packages/webpack-plugin/src/index.ts
`review` 定位的行号有问题

2023-12-14 07:18 UTC, qiYuei approved these changes

2023-12-14 10:05 UTC, kuitos commented on packages/webpack-plugin/src/index.ts
> +        const matchingScriptTags = $('script').filter((_, el) => {
这里可以直接取 srcipt[src] 的标签，不用 filter 里再过滤一遍

2023-12-14 10:07 UTC, merged