feat: add lifecycle check log at development environment (#2604)
umijs/qiankun pull request #2841
Opened 2023-12-12 16:18 UTC by wanghangit

##### Checklist

- [x] `npm test` passes
- [x] tests are included
- [ ] documentation is changed or added
- [x] commit message follows commit guidelines

##### Description of change

link #2604 
add lifecycle log at development environment
output specific errors and prompt compatibility solutions
the log demo is bellow
![log-demo](https://github.com/umijs/qiankun/assets/23646581/aeccc29a-e67d-4761-8a73-348b507a33e4)

2023-12-13 07:56 UTC, kuitos commented on packages/qiankun/src/version.ts
> +export const version = '3.0.0-rc.15';
这个不用提交

2023-12-13 09:24 UTC, kuitos commented on packages/qiankun/src/version.ts
> +export const version = '3.0.0-rc.15';
可以合并一下 next 分支

2023-12-13 09:27 UTC, wanghangit commented on packages/qiankun/src/version.ts
> +export const version = '3.0.0-rc.15';
> 可以合并一下 next 分支

好的，我晚上回去再提一版

2023-12-15 07:51 UTC, wanghangit commented on packages/qiankun/src/version.ts
> +export const version = '3.0.0-rc.15';
已经改好了，辛苦有时间再看看

2023-12-19 08:49 UTC, kuitos requested changes

2023-12-19 08:49 UTC, kuitos commented on packages/qiankun/src/core/loadApp.ts
> +  const validateExportLifecycle = (exports: ObjectType | undefined, nextSourceName: string = ''): boolean => {
可能背景没说清楚，不是在 dev 阶段打日志，是期望在找到不 throw error 的时候提供更多信息，这样监控收集到异常时能有更多的排查线索。

也就是最下面 throw error 时，把尝试获取的 globalLatestSetProp 跟 window['${appName} 打印出来就好了，具体缺哪个导出不用知道了，一般都是成对的缺失，不会只缺一个

2023-12-19 10:44 UTC, wanghangit commented on packages/qiankun/src/core/loadApp.ts
> +  const validateExportLifecycle = (exports: ObjectType | undefined, nextSourceName: string = ''): boolean => {
> 可能背景没说清楚，不是在 dev 阶段打日志，是期望在找到不 throw error 的时候提供更多信息，这样监控收集到异常时能有更多的排查线索。
> 
> 也就是最下面 throw error 时，把尝试获取的 globalLatestSetProp 跟 window['${appName} 打印出来就好了，具体缺哪个导出不用知道了，一般都是成对的缺失，不会只缺一个

好的，明白了，我调整下代码。
globalLatestSetProp 跟 window['${appName} 通过Error打印出来可能是[object Object]，给用户提供更多信息的话，我在想按照具体缺少哪个生命周期的方式提示出来，这样做可能比输出个undefined或[object Object]更有帮助

2023-12-19 12:57 UTC, bravepg commented on packages/qiankun/src/core/loadApp.ts
> +    const isIllegal = illegalKeys.length > 0;
illegal 本身就是形容词，可以直接使用，不需要再用 isXX 的形式了

2023-12-19 12:57 UTC, bravepg commented on packages/qiankun/src/core/loadApp.ts
> +        const warnMsg = illegalKeys
warnMsg 改成 warningMsg 吧

2023-12-19 15:30 UTC, wanghangit commented on .changeset/long-radios-admire.md
> +---
这个文件需要删除吗

2023-12-19 15:32 UTC, wanghangit commented on packages/qiankun/src/core/loadApp.ts
> +    const isIllegal = illegalKeys.length > 0;
好的，已更改

2023-12-20 12:14 UTC, kuitos commented on packages/qiankun/src/core/loadApp.ts
> +  const validateExportLifecycle = (exports: ObjectType | undefined, exportsSource: string): boolean => {
这个方法可以不用改，现在不需要知道具体哪一个导出缺失了，一般都是成对出现，报错时把 globalLatestSetProp 具体的值跟 appName 打出来就行了

2023-12-20 14:47 UTC, wanghangit commented on packages/sandbox/src/patchers/dynamicAppend/common.ts
> +          if (externalSyncMode && !transpiledScriptElement.hasAttribute('src')) {
这里看代码应该是拼错顺手改了

2023-12-20 14:47 UTC, wanghangit commented on packages/qiankun/src/core/loadApp.ts
> +  const validateExportLifecycle = (exports: ObjectType | undefined, exportsSource: string): boolean => {
已还原

2023-12-21 01:30 UTC, kuitos commented on .changeset/long-radios-admire.md
> +---
额看错了原来有两个 changeset😂那需要删掉一个

2023-12-21 02:11 UTC, kuitos approved these changes
LGTM

2023-12-21 02:22 UTC, merged