fix: remove inline script source-url
umijs/qiankun pull request #2850
Opened 2023-12-19 17:04 UTC by wanghangit

##### Checklist

- [x] `npm test` passes
- [x] tests are included
- [ ] documentation is changed or added
- [x] commit message follows commit guidelines

##### Description of change

- resolves https://github.com/umijs/qiankun/issues/2694

2023-12-19 17:07 UTC, wanghangit commented on packages/shared/src/assets-transpilers/__tests__/script.test.ts
> +import { StandardSandbox } from '../../../../sandbox/src/core/sandbox/StandardSandbox';
这里我有些拿不定主意，暂时先写在这里了，shared包不应该依赖其他包
这种被测方法依赖多个包，需要在一个统一的包下测试吗

2023-12-20 02:34 UTC, kuitos commented on packages/shared/src/assets-transpilers/__tests__/script.test.ts
> +import { StandardSandbox } from '../../../../sandbox/src/core/sandbox/StandardSandbox';
不应该依赖，mock一个sandbox出来把

2023-12-20 14:58 UTC, wanghangit commented on packages/shared/src/assets-transpilers/__tests__/script.test.ts
> +      return `;(function(){with(this){${globalObjectOptimizer}${source}\n${sourceMapURL}}}).bind(window.${this.id})();`;
with执行有个疑问，我发现如果source里包含window.xxx这种代码还是直接逃离了沙箱

2023-12-21 01:33 UTC, kuitos commented on packages/shared/src/assets-transpilers/__tests__/script.test.ts
> +      return `;(function(){with(this){${globalObjectOptimizer}${source}\n${sourceMapURL}}}).bind(window.${this.id})();`;
不会的，这个是最基本的隔离

2023-12-21 01:35 UTC, kuitos requested changes

2023-12-21 01:35 UTC, kuitos commented on packages/shared/src/assets-transpilers/__tests__/script.test.ts
> +    makeEvaluateFactory(source: string, sourceURL?: string): string {
这个方法mock可以不用把实现再拷贝一遍，只需要确保单测运行时第二个入参是 undefined 就行

2023-12-21 02:42 UTC, wanghangit commented on packages/shared/src/assets-transpilers/__tests__/script.test.ts
> +      return `;(function(){with(this){${globalObjectOptimizer}${source}\n${sourceMapURL}}}).bind(window.${this.id})();`;
哦，我试了下确实可以因为有window.window对象作为命名空间调用，所以没问题

2023-12-21 04:19 UTC, kuitos approved these changes
Nice work

2023-12-21 04:22 UTC, merged