proxySandbox  code causes the main application to insert style link script errors
umijs/qiankun pull request #875
Opened 2020-08-18 18:48 UTC by SCWR

##### Checklist

- [x] `npm test` passes
- [x] tests are included

##### Description of change
主要修改以下问题

1. npm test 兼容各平台
2. snapshotSandbox sandboxRunning 默认为`ture`，因此首次`active`被调用时直接return 导致 `windowSnapshot` 未被赋值 在首次 `inactive` 时[if (window[prop] !== this.windowSnapshot[prop])](https://github.com/umijs/qiankun/blob/master/src/sandbox/snapshotSandbox.ts#L61)报 `windowSnapshot` `undefined` 错误
3. 解决 各个 sandbox 主框架及子应用 插入 `style` `link` `script` 标签当前环境识别错误问题 主要是主框架识别错误 [相关issues #578](https://github.com/umijs/qiankun/issues/578)

   1. multiple mode proxySandbox

       1. multiple mode `proxySandbox` 下子应用中调用的是`window` 的 `proxy` 代理对象，在获取`document`时，会自动给`document`上自动赋值当前proxy [document[attachDocProxySymbol] = proxy;](https://github.com/umijs/qiankun/blob/master/src/sandbox/proxySandbox.ts#L182)，配合 dynamicAppend 中 [const proxyContainerInfo = proxyContainerInfoMapper.get(this[attachDocProxySymbol]);](https://github.com/umijs/qiankun/blob/master/src/sandbox/patchers/dynamicAppend.ts#L326)来获取子应用的环境配置.
       2. 在子应用下没有问题，但是使用的`document`是原始对象，同时没有相应的释放机制，导致主框架在微应用加载后插入时会读到最后一个微应用`proxy`，插入 `style` `link` `script` 时被误判为相应的微应用环境，导致主框架脚本或样式丢失，
       3. 因此子应用`document`也通过代理去设置，在代理过程中去设置`createElement`，`attachDocProxySymbol`作用更多是标识是否初始化`createElement`，这样在子应用中不会污染到主框架的`createElement`，主框架在插入就不会识别错误

   2. singler mode proxySandbox
       1. 首先 `snapshotSandbox` 及旧版的 `proxySandbox` 共用了一个window实例，导致各个hack方法需要提前赋值.
       2. 因此刷新子应用，从子应用跳转到主应用时，主应用插入 `style` `link` `script` 时，通过[let { appName，appWrapperGetter，proxy，singular，dynamicStyleSheetElements } = opts;](https://github.com/umijs/qiankun/blob/master/src/sandbox/patchers/dynamicAppend.ts#L83)能获取子应用的配置，由于single-spa unmount等操作都是异步的及vue框架下主应用插入时机比浏览器地址切换时机要快[在#578示例里表现是这样](https://github.com/umijs/qiankun/issues/578)，因此通过[checkActivityFunctions(window.location).some(name => name === appName)](https://github.com/umijs/qiankun/blob/master/src/sandbox/patchers/dynamicAppend.ts#L107) 或 `singleSpa.getAppStatus(appName)` 都无法判断是否处于主应用环境，导致主框架脚本或样式丢失.
       3. 旧版的 proxySandbox的proxy模式不够彻底，不能复用multiple mode proxySandbox解决方案，所以在 singler 模式下插入时延迟了一个微任务时差来解决改问题. **由于存在延迟，该方案需要实践验证是否可行** [在#578示例验证通过](https://github.com/umijs/qiankun/issues/578)

close https://github.com/umijs/qiankun/issues/578

2020-08-19 06:28 UTC, kuitos requested changes
感谢你的贡献😃

但是这个 pr 有几个问题：
1. pr 需要能跑通之前的单测，不然就可能触发之前已经解决的问题。
2. #578 的问题是[这个原因](https://github.com/umijs/qiankun/issues/578#issuecomment-635782329)导致的，后续把兼容逻辑应该去掉就可以了 
3. attachDocProxySymbol 赋值覆盖的问题是存在的，可以开一个专门修复的 pr 来处理

2020-08-19 06:28 UTC, kuitos commented on src/sandbox/__tests__/proxySandbox.test.ts
> -  expect(d1).toBe(document);
这个单测逻辑不能改 see https://github.com/umijs/qiankun/pull/846

2020-08-19 06:50 UTC, SCWR commented on src/sandbox/__tests__/proxySandbox.test.ts
> -  expect(d1).toBe(document);
这个是因为 ` 修复 attachDocProxySymbol 的问题是存在的，可以开一个专门修复的 pr 来处理 `  各个子应用已经独立使用 document 代理 因此 单元测试需要修改

[#578](https://github.com/umijs/qiankun/issues/578) 的错误 在 三个沙盒版本都会重现

在 multiple mode proxySandbox 模式 即 新的 proxySandbox 是由于 attachDocProxySymbol 一直没有释放 导致的

在 singler mode 时 是 由于下面导致

 因此刷新子应用，从子应用跳转到主应用时，**主应用插入 `style` `link` `script` 时**，通过[let { appName，appWrapperGetter，proxy，singular，dynamicStyleSheetElements } = opts;](https://github.com/umijs/qiankun/blob/master/src/sandbox/patchers/dynamicAppend.ts#L83)能获取**子应用的配置**，**由于single-spa unmount等操作都是异步的及vue框架下主应用插入时机比浏览器地址切换时机要快**[在#578示例里表现是这样](https://github.com/umijs/qiankun/issues/578)，因此通过[checkActivityFunctions(window.location).some(name => name === appName)](https://github.com/umijs/qiankun/blob/master/src/sandbox/patchers/dynamicAppend.ts#L107) 或 `singleSpa.getAppStatus(appName)` 都无法判断是否处于主应用环境，导致主框架脚本或样式丢失.

2020-08-19 06:54 UTC, SCWR commented
2.0.21 版本 
子应用如果
// const rawCreateElement = document.createElement;

``` js
const rawCreateElement = document.createElement;

document.createElement = function (tabName, opt) {
  console.log('自定义 createElement', this);
  return rawCreateElement(tabName, opt);
};

```
自定义修改了  document.createElement

会导致以下报错

![image](https://user-images.githubusercontent.com/8925282/90602087-c08a9480-e22b-11ea-8ba0-34b04071336a.png)

2020-08-19 07:13 UTC, SCWR commented on src/sandbox/__tests__/proxySandbox.test.ts
> -  expect(d1).toBe(document);
果然都是要填的坑...

2020-08-19 07:28 UTC, SCWR commented on src/sandbox/__tests__/proxySandbox.test.ts
> -  expect(d1).toBe(document);
我猜测 head.ownerDocument.createElement 不会触发  
``` js
   // mark the symbol to document while accessing as document.createElement could know is invoked by which sandbox for dynamic append patcher	        
        if (p === 'document') {
          document[attachDocProxySymbol] = proxy;	
          return document;
        }
```

2020-08-19 08:17 UTC, kuitos commented
> const rawCreateElement = document.createElement;
> 
> document.createElement = function (tabName, opt) {
>   console.log('自定义 createElement', this);
>   return rawCreateElement(tabName, opt);
> };

这个报错跟 qiankun 没关系，你可以控制台试下

2020-08-19 08:47 UTC, SCWR commented
> > const rawCreateElement = document.createElement;
> > document.createElement = function (tabName, opt) {
> > console.log('自定义 createElement', this);
> > return rawCreateElement(tabName, opt);
> > };
> 
> 这个报错跟 qiankun 没关系，你可以控制台试下

我试了一下 结果如图

![GIF 2020-8-19 16-45-04](https://user-images.githubusercontent.com/8925282/90613131-89bc7a80-e23b-11ea-8e30-bd68e8b5c38e.gif)

2020-08-19 11:03 UTC, kuitos commented
不需要特地在 qiankun 环境下跑，随便找个地方 chrome 控制台里就可以了，因为这个实现本身就是有问题的..
![image](https://user-images.githubusercontent.com/5206843/90627480-94ccd600-e24e-11ea-9aa4-9c212fc1b532.png)

2020-08-19 12:09 UTC, SCWR commented
额 好吧 
请查看这里
snapshotSandbox sandboxRunning 默认为ture，因此首次active被调用时直接return 导致 windowSnapshot 未被赋值 在首次 inactive 时if (window[prop] !== this.windowSnapshot[prop])报 windowSnapshot undefined 错误
看看是不是存在该问题
然后你觉得OK 可以关闭PR了

2020-08-20 02:17 UTC, kuitos commented
> snapshotSandbox sandboxRunning 默认为ture，因此首次active被调用时直接return 导致 windowSnapshot 未被赋值 在首次 inactive 时if (window[prop] !== this.windowSnapshot[prop])报 windowSnapshot undefined 错误

这确实是个 bug，把 active 里的 if 判断去掉就可以了。来个 pr？

2020-08-20 03:13 UTC, SCWR commented
> > snapshotSandbox sandboxRunning 默认为ture，因此首次active被调用时直接return 导致 windowSnapshot 未被赋值 在首次 inactive 时if (window[prop] !== this.windowSnapshot[prop])报 windowSnapshot undefined 错误
> 
> 这确实是个 bug，把 active 里的 if 判断去掉就可以了。来个 pr？

好的 我先关闭这个pr 

attachDocProxySymbol  这个问题 我都想炸了  期待你有解决方案 感觉 proxy document 是条解决之路 就是可能需要花精力去专门维护代理所带来的坑

2020-08-20 03:13 UTC, closed without merging

2020-08-20 06:19 UTC, kuitos commented
> attachDocProxySymbol 这个问题 我都想炸了 期待你有解决方案 感觉 proxy document 是条解决之路 就是可能需要花精力去专门维护代理所带来的坑

document 的 getter 做成「阅完即焚」就好了，一会我提个 pr

2020-08-20 14:11 UTC, SCWR commented
> > attachDocProxySymbol 这个问题 我都想炸了 期待你有解决方案 感觉 proxy document 是条解决之路 就是可能需要花精力去专门维护代理所带来的坑
> 
> document 的 getter 做成「阅完即焚」就好了，一会我提个 pr

嗯 请注意存在使用window.document(会赋值）
不调用createElement（阅后即焚）的情况