:bug: Allows the use of tag elements during script tag trigger events
umijs/qiankun pull request #914
Opened 2020-09-07 09:17 UTC by wangzongxu

##### Checklist

- [x] `npm test` passes
- [ ] tests are included
- [ ] documentation is changed or added
- [x] commit message follows commit guidelines

##### Description of change

当我们在接入qiankun的时候，
发现其中的一个子项目有报错，
跟踪堆栈发现，是因为那个子项目中对于script标签都进行了onload事件监听，
并且使用了事件对象的target属性来获取src。

下面是伪代码：
```js
srcipt.onload = function(e) {
  console.log(e.target.src)
}
```

由于qiankun派发的自定义事件中没有定义target，
所以报错了，
这个PR中的getPatchedCustomEvent方法为以后可能需要添加更多属性提供了准备。

2020-09-08 04:32 UTC, kuitos requested changes
Thanks for your nice work!

2020-09-08 04:32 UTC, kuitos commented on src/sandbox/patchers/dynamicAppend.ts
> +function getPatchedCustomEvent(type: string, element: HTMLScriptElement): CustomEvent {
第二个参数改成 elementGetter 吧，elementGetter: () => HTMLScriptElement，从而确保 next task 时通过 e.target 取到的 element 是已被置为 null 的

2020-09-08 04:36 UTC, kuitos requested changes

2020-09-08 04:36 UTC, kuitos commented on src/sandbox/patchers/dynamicAppend.ts
> +                const loadEvent = getPatchedCustomEvent('load', element);
这个逻辑应该只在 element.onload 调用场景生效，element.dispatchEvent 不应该再做这类事情。

方法改为 patchedCustomEvent 吧，只在 element.onload 跟 element.onerror 时把 event 里写入 target 这些属性

2020-09-08 06:37 UTC, wangzongxu commented on src/sandbox/patchers/dynamicAppend.ts
> +function getPatchedCustomEvent(type: string, element: HTMLScriptElement): CustomEvent {
我怎么觉得elementGetter的类型是 () => HTMLScriptElement | null 呢，在next task之后element为null，是手误吗。

2020-09-09 02:39 UTC, kuitos approved these changes

2020-09-09 02:39 UTC, kuitos commented on src/sandbox/patchers/dynamicAppend.ts
> +function patchedCustomEvent(e: CustomEvent, elementGetter: () => HTMLScriptElement | null): CustomEvent {
```suggestion
function patchCustomEvent(e: CustomEvent, elementGetter: () => HTMLScriptElement | null): CustomEvent {
```

2020-09-09 02:39 UTC, kuitos commented on src/sandbox/patchers/dynamicAppend.ts
> +                  element.onload(patchedCustomEvent(loadEvent, () => element));
```suggestion
                  element.onload(patchCustomEvent(loadEvent, () => element));
```

2020-09-09 02:39 UTC, kuitos commented on src/sandbox/patchers/dynamicAppend.ts
> +                  element.onerror(patchedCustomEvent(errorEvent, () => element));
```suggestion
                  element.onerror(patchCustomEvent(errorEvent, () => element));
```

2020-09-09 02:47 UTC, kuitos approved these changes

2020-09-09 02:49 UTC, merged