doc: add some frequently questions to the FAQ
umijs/qiankun pull request #948
Opened 2020-09-22 15:13 UTC by gongshun

### Checklist

- [x] documentation is changed or added

##### Description of change

补充几个常见问题

2020-09-24 11:08 UTC, kuitos requested changes
commit 有点问题，rebase 一下到 master 分支吧

2020-09-24 11:08 UTC, kuitos commented on docs/faq/README.zh.md
> ++ <script src="//yourhost/entry.js" entry />
script 标签不是自闭和的

2020-09-24 11:15 UTC, kuitos requested changes

2020-09-24 11:15 UTC, kuitos commented on docs/api/README.zh.md
> +      - 配置为字符串时，表示微应用的访问地址。如果微应用部署在二级目录，则最后面的 `/` 不可省略。例如，微应用的访问地址是：`https://qiankun.umijs.org/guide`，那么 `entry` 应该是 `https://qiankun.umijs.org/guide/`。
尾部 slash 要不要省略建议写到 FAQ 或者 cookbook 里关于二级目录方式部署的章节吧，因为不是所有通过 https://qiankun.umijs.org/guide 访问的场景都需要加 slash，需要更精确的一些特定场景描述，不然在这里看到 api 描述的用户可能会选择无脑加，最后造成其他问题

2020-09-24 11:29 UTC, gongshun commented on docs/faq/README.zh.md
> ++ <script src="//yourhost/entry.js" entry />
不这样写会有bug，你看官网：https://qiankun.umijs.org/zh/faq#%E9%9D%9E-webpack-%E6%9E%84%E5%BB%BA%E7%9A%84%E5%BE%AE%E5%BA%94%E7%94%A8%E6%94%AF%E6%8C%81%E6%8E%A5%E5%85%A5-qiankun-%E4%B9%88%EF%BC%9F 。奇怪的是只有中文版这样，英文版没事

![image](https://user-images.githubusercontent.com/29347231/94139451-3b367780-fe9c-11ea-99cf-c034bd4e2343.png)

2020-09-24 11:30 UTC, gongshun commented on docs/api/README.zh.md
> +      - 配置为字符串时，表示微应用的访问地址。如果微应用部署在二级目录，则最后面的 `/` 不可省略。例如，微应用的访问地址是：`https://qiankun.umijs.org/guide`，那么 `entry` 应该是 `https://qiankun.umijs.org/guide/`。
好的，这是上次提交的，我修改一下

2020-09-27 03:18 UTC, kuitos commented on docs/faq/README.zh.md
> ++ <script src="//yourhost/entry.js" entry />
@PeachScript 这个问题知道不

2020-09-27 03:24 UTC, kuitos requested changes

2020-09-27 03:24 UTC, kuitos commented on docs/faq/README.zh.md
> +修改一下 `webpack` 打包，给字体文件注入路径前缀即可：
更 prefer 的方式应该是在一定大小以内的都通过 base64 打进去

2020-09-27 03:26 UTC, PeachScript commented on docs/faq/README.zh.md
> ++ <script src="//yourhost/entry.js" entry />
> @PeachScript 这个问题知道不

应该是 dumi 1.0 的 bug，我提个 PR 升级到 1.1 beta

2020-09-27 11:50 UTC, gongshun commented on docs/faq/README.zh.md
> +修改一下 `webpack` 打包，给字体文件注入路径前缀即可：
好的，我补充一下。另外，给官网设计个 icon 呗。
![image](https://user-images.githubusercontent.com/29347231/94364288-b85f2800-00fa-11eb-8d9b-7b9ef1dc7d04.png)

2020-09-30 03:40 UTC, gongshun commented on docs/faq/README.zh.md
> +修改一下 `webpack` 打包，给字体文件注入路径前缀即可：
@kuitos 已经补充了：4kb 以内的字体文件打包成 base64 。看了下 vue-cli4 ，它给的大小限制就是4kb

2020-10-09 03:39 UTC, kuitos commented on docs/faq/README.zh.md
> ++ <script src="//yourhost/entry.js" entry />
升到 beta 就好了 https://github.com/umijs/qiankun/pull/974

2020-10-09 03:40 UTC, kuitos approved these changes

2020-10-09 03:40 UTC, merged