新增vue3.0 demo
umijs/qiankun pull request #950
Opened 2020-09-24 04:59 UTC by Chaunjie

##### Checklist

- [ ] `npm test` passes
- [ ] tests are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

- any feature?
- close https://github.com/umijs/qiankun/ISSUE_URL

2020-09-27 03:17 UTC, kuitos commented
@gongshun review 一下

2020-09-27 11:56 UTC, gongshun requested changes
不要修改其他的文件的格式。

2020-09-27 12:08 UTC, gongshun commented on examples/vue3/src/main.js
> +import './public-path';
必须在文件开头引入 `public-path.js`

2020-09-27 12:08 UTC, gongshun commented on examples/vue3/src/main.js
> +function render() {
render 函数的写法参考 vue 项目，需要使用 container 避免 id 冲突，而且你这个路由并不能销毁，销毁的是引用，而不是路由实例

2020-09-27 12:08 UTC, gongshun commented on examples/vue3/src/main.js
> +export async function unmount() {
没有清空 dom 的引用

2020-09-27 12:51 UTC, Chaunjie commented on examples/vue3/src/main.js
> +export async function unmount() {
好的，我修改一个版本

2020-09-27 13:49 UTC, Chaunjie commented on examples/vue3/src/main.js
> +export async function unmount() {
@gongshun 按照你说的要求改了下，重新提交了一个版本

2020-09-27 14:56 UTC, gongshun commented on examples/vue3/src/main.js
> +export async function unmount() {
销毁实例的写法有点问题，按这个写：
```js
instance.unmount();
instance._container.innerHTML = '';
```
主项目菜单更新一下，`example.gif` 更新一下，子项目的内容修改下吧，改成普通的 home 页面和 about 页面

2020-09-28 02:58 UTC, Chaunjie commented on examples/vue3/src/main.js
> +export async function unmount() {
@gongshun ，按照要求都更新了，麻烦你再review一下

2020-09-28 04:45 UTC, gongshun commented on examples/vue3/src/main.js
> +export async function unmount() {
example.gif 截图有水印，其他的没啥了

2020-09-28 05:19 UTC, Chaunjie commented on examples/vue3/src/main.js
> +export async function unmount() {
好的，晚上我再录频一次，公司电脑有水印

2020-09-28 16:15 UTC, Chaunjie commented on examples/vue3/src/main.js
> +export async function unmount() {
@gongshun 我重新录制了一个gif，麻烦你再看下

2020-09-29 13:35 UTC, Chaunjie commented on examples/vue3/src/main.js
> +export async function unmount() {
@gongshun 麻烦再看一下

2020-09-30 02:39 UTC, Chaunjie commented on package.json
> +    "examples:start-multiple": "run-p start:main-multiple start:react15 start:vue start:vue3",
@gongshun 我重新提交了一个版本，你再看下

2020-09-30 02:40 UTC, gongshun commented
OK，我这边没有其他的问题了， @kuitos 你再确认下？

2020-10-09 03:53 UTC, kuitos commented
有很多对其他 example 格式化的变更，这些能 revert 掉么，一个 pr 只做一件事情吧，不然别人 review 起来很困难 @Chaunjie

2020-10-09 06:48 UTC, Chaunjie commented
> 有很多对其他 example 格式化的变更，这些能 revert 掉么，一个 pr 只做一件事情吧，不然别人 review 起来很困难 @Chaunjie

@kuitos 其他项目的文件我没有改动到，我本地试了下，貌似是pre-commit引起的校验和修改

2020-10-09 07:37 UTC, kuitos commented
按理 prettier 只会对改动的文件做格式化，可能是你的编辑器做了其他设置吧

手动处理下？没改动的不用 commit 了

2020-10-09 07:41 UTC, Chaunjie commented
> 按理 prettier 只会对改动的文件做格式化，可能是你的编辑器做了全局设置？
> 
> 手动处理下？没改动的不用 commit 了

有可能读取了我全局的eslint配置，我先修改下，改成项目设置的看看

2020-10-09 10:08 UTC, Chaunjie commented
@kuitos 这边我关闭了，我重新提交一个PR

2020-10-09 10:08 UTC, closed without merging